### ISSUE TITLE
HW design files?

### ISSUE THREAD

**Issue by peci1** [altineller/fximu2#1]
On ROS discourse, you called this an open hardware project. Do you plan to also release the HW design files?

**Comment by joekeo** [comment]
Second this, This IMU seems very good, such a nice piece of work.
I would like to get my hands on (at least) one board to test it. 
If HW file are not available, can I buy a board off you?

**Comment by altineller** [comment]
@peci1 @joekeo Hello, I prepared a new version, that includes a secondary i2c port for addition of a satellite sensor, as well as cosmetic changes. I will be releasing hardware diagram soon.

Meanwhile I am sending people PCB board, all you need to do is purchase the parts from an electronic distributor, and then find someone at a local hackerspace that can do SMD soldering.

Please send me your addresses to altineller@gmail.com and I will ship the PCB's as soon as I can.

Best regards,
Can

**Comment by peci1** [comment]
Thanks, I'll wait for the design files, that's no problem for me ;)

**Comment by altineller** [comment]
@peci1

The eagle schematics, pcb design, and gerbers available at: http://github.com/altineller/fximu_hardware 

I will post the v2 as soon as I finish it, after I send it to board house.

Best regards,
Can
